name: Build APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libtinfo6
        sudo apt-get install -y android-sdk
        sudo apt-get install -y android-sdk-platform-tools
        sudo apt-get install -y android-sdk-build-tools
        sudo apt-get install -y android-sdk-cmdline-tools
        pip install cython
        run: |
          yes | sdkmanager "build-tools;34.0.0"  # Replace with your version
          echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

    - name: Install Buildozer
      run: pip install buildozer

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ./path/to/artifact
