name: Build APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libtinfo6
        sudo apt-get install -y android-sdk
        sudo apt-get install -y android-sdk-platform-tools
        sudo apt-get install -y android-sdk-build-tools
        pip install cython

    - name: Setup Android SDK
      run: |
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        cd $HOME/Android/Sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-10406996_latest.zip -d latest
        echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0"
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-34"
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "extras;android;m2repository"
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk-bundle"
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "extras;google;aidl"
        echo "$ANDROID_HOME/build-tools/34.0.0" >> $GITHUB_PATH

    - name: Validate XML files
      run: find . -name "*.xml" -exec xmllint --noout {} \;

    - name: Install Buildozer
      run: pip install buildozer

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ./path/to/artifact
